---
openapi: 3.0.0
info:
  title: Votesmart API
  description: Votesmart API
  contact:
    email: you@your-company.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/MATT_23/votesmartapi/1.0.0
  description: SwaggerHub API Auto Mocking
tags:
- name: candidates
  description: This object represents a candidate's biographical data.
- name: bills
  description: This object represents a bill.
- name: elections
  description: this object represents an election.
- name: ballots
  description: this object represents a list of state ballot measures.
paths:
  /candidates/{candidateId}:
    get:
      tags:
      - candidates
      summary: retrieves information on an individual candidate.
      description: By passing in a candidateId, you can retrieve biographical information on a specific candidate currently running for office at the state or federal level, and a politician currently holding state of federal office.
      operationId: searchCandidate
      parameters:
      - name: candidateId
        in: path
        description: unique identifer for the candidate.
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: search results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CandidateItem'
        "400":
          description: bad input parameter
  /bills/{billId}:
    get:
      tags:
      - bills
      summary: get info on a bill.
      description: Retrieves detailed information on a specific bill.
      operationId: searchBill
      parameters:
      - name: billId
        in: path
        description: Retrieves detailed information on a specific bill including the stage details, timeline, and vote results.
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: bill matching billId
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BillItem'
        "400":
          description: invalid input, object invalid
  /elections/{electionId}:
    get:
      tags:
      - elections
      summary: get info on an election.
      description: Retrieves detailed information on a specific election.
      operationId: searchElection
      parameters:
      - name: electionId
        in: path
        description: Retrieves detailed information on a specific election including the candidates and their party affiliation.
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: election matching electionId.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ElectionItem'
        "400":
          description: invalid input, object invalid
  /ballots/{stateId}/{year}:
    get:
      tags:
      - ballots
      summary: get info on a single ballot measure detail.
      description: Retrieves detailed information on a specific ballot measuure detail.
      operationId: searchBallot
      parameters:
      - name: stateId
        in: path
        description: Retrieves detailed information on a specific ballot measure.
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: year
        in: path
        description: ballot year
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      responses:
        "200":
          description: election matching electionId.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BallotMeasures'
        "400":
          description: invalid input, object invalid
components:
  schemas:
    CandidateItem:
      required:
      - birthPlace
      - birthdate
      - family
      - firstName
      - id
      - lastName
      - middleName
      - religion
      type: object
      properties:
        id:
          type: string
          format: uuid
        firstName:
          type: string
          example: Barack
        middleName:
          type: string
          example: Hussein
        lastName:
          type: string
          example: Obama
        birthDate:
          type: string
          format: date-time
        family:
          $ref: '#/components/schemas/Family'
    Family:
      required:
      - name
      type: object
      properties:
        wife:
          type: string
          example: Michelle
        children:
          $ref: '#/components/schemas/Children'
    Children:
      type: array
      items:
        $ref: '#/components/schemas/Child'
    Child:
      type: object
      properties:
        name:
          type: string
          example: Sasha
    BillItem:
      type: object
      properties:
        bill:
          $ref: '#/components/schemas/GeneralInfo'
        billNumber:
          type: string
          example: HR 3005
        parentBill:
          type: string
          example: ""
        title:
          type: string
          example: To direct the Joint Committee on the Library to replace the bust of Roger Brooke Taney in the Old Supreme Court Chamber of the United States Capitol with a bust of Thurgood Marshall to be obtained by the Joint Committee on the Library and to remove certain statues from areas of the United States Capitol which are accessible to the public, to remove all statues of individuals who voluntarily served the Confederate States of America from display in the United States Capitol, and for other purposes.
    GeneralInfo:
      type: object
      properties:
        title:
          type: string
          example: Project Vote Smart - Keyvote - HR 3005 - To direct the Joint Committee on the Library to replace the bust of Roger Brooke Taney in the Old Supreme Court Chamber of the United States Capitol with a bust of Thurgood Marshall to be obtained by the Joint Committee on the Library and to remove certain statues from areas of the United States Capitol which are accessible to the public, to remove all statues of individuals who voluntarily served the Confederate States of America from display in the United States Capitol, and for other purposes.
        linkBack:
          type: string
          example: http://votesmart.org/issue_keyvote_detail.php?cs_id=80784
    ElectionItem:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 137829
        title:
          type: string
          example: Alaska U.S. Senate
        date:
          type: string
          example: Nov.8, 2022
        stage:
          type: string
          example: General
        office:
          type: string
          example: Congressional
        candidates:
          type: array
          items:
            $ref: '#/components/schemas/ElectionCandidate'
    ElectionCandidate:
      type: object
      properties:
        name:
          type: string
          example: Patricia Chesbro
        result:
          type: string
          example: Too Close To Call
        party:
          type: string
          example: Democratic
    BallotMeasures:
      type: object
      properties:
        title:
          type: string
          example: 'SB 8008 - Proposition 1: Environment and Climate Change Projects Bond Measure'
        date:
          type: string
          example: Nov. 8, 2022
        outcome:
          type: string
          example: Passed
        categories:
          type: string
          example: Environment
        summary:
          type: string
          example: Enacts into law major components of legislation necessary to implement the state transportation, economic development and environmental conservation budget for the 2022-2023 state fiscal year.
        fulltext:
          type: string
          example: https://www.nysenate.gov/legislation/bills/2021/S8008
